### ISSUE TITLE
ISO C99 doesn't support unnamed structs/unions

### ISSUE THREAD

**Issue by nemequ** [ebiggers/libdeflate#10]
See quixdb/squash#199 for a bit of background.  If you compile with GCC 4.4 in C99 mode it will result in an error; GNU99 mode works, but if you tell CMake that you want to use the C99 standard it will pass -std=c99 not -std=gnu99… regardless, apparently it's not valid C99 so it would probably be wise to change the code for portability reasons.

-Wpedantic should trigger the warning, assuming you're compiling in C99 mode.  With GCC 4.4 (on CentOS 6), with -std=c99 (and no -Wpedantic), I get:

```
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:170: warning: declaration does not declare anything
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:171: warning: declaration does not declare anything
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:357: warning: declaration does not declare anything
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:383: warning: declaration does not declare anything
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:385: warning: declaration does not declare anything
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_make_huffman_codes’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1113: error: ‘struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1119: error: ‘struct deflate_lens’ has no member named ‘offset’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_write_huffman_codes’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1320: error: ‘struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1326: error: ‘struct deflate_lens’ has no member named ‘offset’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1337: error: ‘struct deflate_lens’ has no member named ‘offset’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1341: error: ‘struct deflate_lens’ has no member named ‘all’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1342: error: ‘struct deflate_lens’ has no member named ‘all’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1343: error: ‘struct deflate_lens’ has no member named ‘all’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1347: error: ‘struct deflate_lens’ has no member named ‘all’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1352: error: ‘struct deflate_lens’ has no member named ‘all’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1353: error: ‘struct deflate_lens’ has no member named ‘all’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1354: error: ‘struct deflate_lens’ has no member named ‘all’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_write_sequences’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1381: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1386: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1391: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1396: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1403: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1409: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1415: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1447: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1464: error: ‘const struct deflate_lens’ has no member named ‘offset’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_write_end_of_block’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1486: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_write_block’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1520: error: ‘struct deflate_compressor’ has no member named ‘sequences’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_compress_greedy’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1592: error: ‘struct deflate_compressor’ has no member named ‘sequences’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1607: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1609: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1623: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1637: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1656: error: ‘struct deflate_compressor’ has no member named ‘sequences’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_compress_lazy’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1689: error: ‘struct deflate_compressor’ has no member named ‘sequences’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1706: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1708: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1727: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1752: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1781: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1804: error: ‘struct deflate_compressor’ has no member named ‘sequences’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1816: error: ‘struct deflate_compressor’ has no member named ‘hc_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1834: error: ‘struct deflate_compressor’ has no member named ‘sequences’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_tally_item_list’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1862: error: ‘struct deflate_compressor’ has no member named ‘optimum’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_write_item_list’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1894: error: ‘struct deflate_compressor’ has no member named ‘optimum’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1906: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1913: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1928: error: ‘const struct deflate_lens’ has no member named ‘offset’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_set_costs’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1949: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1949: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1950: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1957: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1957: error: ‘const struct deflate_lens’ has no member named ‘litlen’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1959: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1964: error: ‘const struct deflate_lens’ has no member named ‘offset’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1964: error: ‘const struct deflate_lens’ has no member named ‘offset’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:1966: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_set_default_costs’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2011: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2015: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2020: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_adjust_costs’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2045: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2050: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2056: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_optimize_and_write_block’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2067: error: ‘struct deflate_compressor’ has no member named ‘optimum’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2068: error: ‘struct deflate_compressor’ has no member named ‘num_optim_passes’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2104: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2133: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2136: error: ‘struct deflate_compressor’ has no member named ‘costs’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2148: error: ‘struct deflate_compressor’ has no member named ‘optimum’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_compress_near_optimal’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2206: error: ‘struct deflate_compressor’ has no member named ‘bt_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2216: error: ‘struct deflate_compressor’ has no member named ‘cached_matches’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2217: error: ‘struct deflate_compressor’ has no member named ‘cached_matches’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2246: error: ‘struct deflate_compressor’ has no member named ‘bt_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2274: error: ‘struct deflate_compressor’ has no member named ‘bt_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2316: error: ‘struct deflate_compressor’ has no member named ‘bt_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2322: error: ‘struct deflate_compressor’ has no member named ‘bt_mf’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_alloc_compressor’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2393: error: ‘struct deflate_compressor’ has no member named ‘optimal_end’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2396: error: ‘struct deflate_compressor’ has no member named ‘nonoptimal_end’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2445: error: ‘struct deflate_compressor’ has no member named ‘num_optim_passes’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2451: error: ‘struct deflate_compressor’ has no member named ‘num_optim_passes’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2457: error: ‘struct deflate_compressor’ has no member named ‘num_optim_passes’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2463: error: ‘struct deflate_compressor’ has no member named ‘num_optim_passes’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2469: error: ‘struct deflate_compressor’ has no member named ‘num_optim_passes’
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c: In function ‘deflate_compress’:
/home/nemequ/squash/plugins/libdeflate/libdeflate/src/deflate_compress.c:2506: error: ‘struct deflate_compressor’ has no member named ‘sequences’
make[2]: *** [plugins/libdeflate/CMakeFiles/squash0.8-plugin-libdeflate.dir/libdeflate/src/deflate_compress.c.o] Error 1
make[1]: *** [plugins/libdeflate/CMakeFiles/squash0.8-plugin-libdeflate.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ebiggers** [comment]
Fixed.
